### ISSUE TITLE
why did you hardcoded the response?

### ISSUE THREAD

**Issue by S0c5** [julian-linux/web-component-angular#2]
https://github.com/julian-linux/web-component-angular/blob/5859a6589f3a1aadc55d2f26cac0dbb74014f322/src/app/tweet.service.ts#L20

**Comment by julian-linux** [comment]
Because i had problems with the API twitter. They dont send me the txt for activate my dev account and I dont had time because it was a test. So i talked with the company and they let me hardcoded the response.
