### ISSUE TITLE
why this console.log and comments?

### ISSUE THREAD

**Issue by S0c5** [julian-linux/web-component-angular#3]
https://github.com/julian-linux/web-component-angular/blob/5859a6589f3a1aadc55d2f26cac0dbb74014f322/src/app/app.component.ts#L43

https://github.com/julian-linux/web-component-angular/blob/5859a6589f3a1aadc55d2f26cac0dbb74014f322/src/app/app.component.ts#L36

**Comment by julian-linux** [comment]
I just forgot remove it
